-- (CREATE DATABASE)
CREATE DATABASE EMPLOYEE;

-- (USE DATABASE)
USE EMPLOYEE;

-- (CREATE TABLE)
CREATE TABLE EMP (
    EMPNO VARCHAR(20),
    ENAME VARCHAR(100),
    JOB VARCHAR(100),
    HIREDATE DATE,
    SAL INT
);

-- (INSERT VALUES IN TABLE)
INSERT INTO EMP (EMPNO, ENAME, JOB, HIREDATE, SAL) VALUES
(7839, 'KING', 'PRESIDENT', '1981-11-17', 5000),
(7698, 'BLAKE', 'MANAGER', '1981-05-01', 2850),
(7782, 'CLARK', 'MANAGER', '1981-06-09', 2450),
(7566, 'JONES', 'MANAGER', '1981-04-02', 2975),
(7788, 'SCOTT', 'ANALYST', '1982-12-09', 3000),
(7902, 'FORD', 'ANALYST', '1981-12-03', 3000),
(7369, 'SMITH', 'CLERK', '1980-12-17', 800),
(7499, 'ALLEN', 'SALESMAN', '1981-02-20', 1600),
(7521, 'WARD', 'SALESMAN', '1981-02-22', 1250),
(7654, 'MARTIN', 'SALESMAN', '1981-09-28', 1250),
(7844, 'TURNER', 'SALESMAN', '1981-09-08', 1500),
(7876, 'ADAMS', 'CLERK', '1983-01-12', 1100),
(7900, 'JAMES', 'CLERK', '1981-12-03', 950),
(7934, 'MILLER', 'CLERK', '1982-01-23', 1300);

/*  (ORDER WHILE WRITING QUERY)
FROM
SELECT
OORDER BY
LIMIT
*/


-- (Please write a query that retrieves the following columns from the EMP table: JOB,ENAME,SAL,HIREDATE)
SELECT JOB,ENAME,SAL,HIREDATE FROM EMP;

/*
(Aliasing Columns
Please write a query that retrieves the following columns (in uppercase) from the EMP table: 
ENAME as EMPLOYEE_NAME , JOB as JOB_TITLE , SAL as MONTHLY_SALARY)
*/
SELECT ENAME AS EMPLOYEE_NAME, JOB AS JOB_TITLE, SAL AS MONTHLY_SALARY FROM EMP;

/* (Top 5 Salaries  Please write a query that displays the top 5 salaries in descending order.
 In your result return all columns from the EMP table.)*/
SELECT * FROM EMP ORDER BY SAL DESC LIMIT 5;

SELECT COUNTRY_ID ,COUNTRY_NAME AS NAME FROM COUNTRIES.COUNTRIES ORDER BY NAME;
SELECT COUNTRY_ID ,COUNTRY_NAME AS NAME FROM COUNTRIES.COUNTRIES ORDER BY COUNTRY_NAME;


/*
CREATE TABLE [IF NOT EXISTS] SCHEMA.TABLE(
	COLUMN1 DATATYPE [CONSTRAINTS],
    COLUMN2 DATATYPE [CONSTRAINTS],
    COLUMN2 DATATYPE [CONSTRAINTS],
    ...
);
*/
-- CREATING THE TEST TABLE IN COUNTRIES DATABASE 
CREATE TABLE IF NOT EXISTS COUNTRIES.TEST(COL1 VARCHAR(2),COL2 INT);
DROP TABLE IF EXISTS COUNTRIES.TEST;


CREATE DATABASE TEMP_SCHEMA;
CREATE TABLE TEMP_SCHEMA.TABLE_1 (COL_STRING VARCHAR(255),COL_NUM NUMERIC(10,2),COL DATE);

-- (AFTER RUNNING N NUMBER OF TIMES IT IS ADDING THE SAME ROW FOR N TIMES SO TO AVOID THIS WE USE CONSTRAINTS)
INSERT INTO TEMP_SCHEMA.TABLE_1 VALUES('HELLO',123.56,'2004-10-12');

DESC TEMP_SCHEMA.TABLE_1 ;

SELECT * FROM TEMP_SCHEMA.TABLE_1 ;

-- (GIVES NO ERROR EVEN THOUGH VALUES ARE NOT CORRECT , TO AVOID THIS USE CONSTRSINT)
INSERT INTO TEMP_SCHEMA.TABLE_1 VALUES('',NULL,'2004-10-12');
SELECT * FROM TEMP_SCHEMA.TABLE_1 ;

CREATE TABLE TEMP_SCHEMA.TABLE_2(COL_STRING VARCHAR(255),COL_NUM NUMERIC(10,2),COL DATE);
CREATE TABLE TEMP_SCHEMA.TABLE_3(COL_NUM NUMERIC(10,2),COL DATE,COL_STRING VARCHAR(255));

-- (COPY ALL THE COLUMNS FROM TABLE-1 TO TABLE-2 BECAUSE THEY HAVE SAME ORDER AND SAME COLUMNS)
INSERT INTO TEMP_SCHEMA.TABLE_2
SELECT * FROM TEMP_SCHEMA.TABLE_1;

SELECT * FROM TEMP_SCHEMA.TABLE_2;


-- (IT GIVES ERROR BECAUSE THE ORDER OF TABLE-2 AND TABLE-3 IS NOT SAME)
INSERT INTO TEMP_SCHEMA.TABLE_3
SELECT * FROM TEMP_SCHEMA.TABLE_2;

INSERT INTO TEMP_SCHEMA.TABLE_3 (COL_STRING,COL_NUM,COL)  -- (THIS WILL EXECUTE AS WE ARE CHANGING ORDER OF TABLE-3)
SELECT * FROM TEMP_SCHEMA.TABLE_2;


/*
CREATE TABLE SCHEMA.TABLE1 AS
(SELECT STATEMENT);
*/   -- (CREATING STRUCTURE OF NEW_TABLE BY COPYING STRUCTRE OF OLD TABLE)
CREATE TABLE TEMP_SCHEMA.DEMO_1 AS
SELECT * FROM TEMP_SCHEMA.TABLE_1;
DESC TEMP_SCHEMA.DEMO_1;
SELECT * FROM TEMP_SCHEMA.DEMO_1;







